### ISSUE TITLE
Mailin crashes, if email has attachments, but one it's empty.

### ISSUE THREAD

**Issue by tomkovicsb** [Flolagale/mailin#101]
Mailin fails to process an email if the mail has attachments, but one of the attachment's is empty.
This is the exact code section where the problem occurs:

`finalizedMessage.attachments.forEach(function (attachment) {
attachmentNamesAndContent[attachment.generatedFileName] = attachment.content.toString('base64');
delete attachment.content;
});`

If one of the attachment's content is null or undefined (Yes it can happen!) then the error, down below occurs:

`"error: b6da5fa4-f769-418c-935d-aa709474c26a Unable to finish processing message!! TypeError: Cannot read property 'toString' of undefined\n
    at /usr/lib/node_modules/mailin/lib/mailin.js:375:93\n
    at Array.forEach (native)\n
    at /usr/lib/node_modules/mailin/lib/mailin.js:374:42\n
    at tryCatcher (/usr/lib/node_modules/mailin/node_modules/bluebird/js/main/util.js:26:23)\n
    at Promise._resolveFromResolver (/usr/lib/node_modules/mailin/node_modules/bluebird/js/main/promise.js:480:31)\n
    at new Promise (/usr/lib/node_modules/mailin/node_modules/bluebird/js/main/promise.js:70:37)\n
    at postWebhook (/usr/lib/node_modules/mailin/lib/mailin.js:363:16)\n
    at tryCatcher (/usr/lib/node_modules/mailin/node_modules/bluebird/js/main/util.js:26:23)\n
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/mailin/node_modules/bluebird/js/main/promise.js:507:31)\n
    at Promise._settlePromiseAt (/usr/lib/node_modules/mailin/node_modules/bluebird/js/main/promise.js:581:18)\n
    at Promise._settlePromises (/usr/lib/node_modules/mailin/node_modules/bluebird/js/main/promise.js:697:14)\n
    at Async._drainQueue (/usr/lib/node_modules/mailin/node_modules/bluebird/js/main/async.js:123:16)\n
    at Async._drainQueues (/usr/lib/node_modules/mailin/node_modules/bluebird/js/main/async.js:133:10)\n
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/mailin/node_modules/bluebird/js/main/async.js:15:14)\n
    at processImmediate [as _immediateCallback] (timers.js:383:17)\n"`

Please fix it as soon as possible.

**Comment by Flolagale** [comment]
@tomkovicsb I won't have the time to do it soon, so please feel free to submit a PR, I'll be happy to merge it.

**Comment by rightfold** [comment]
This problem still exists, I'll see if I can do a PR on Monday.
