### ISSUE TITLE
Unable to finish processing message: ENOENT .tmp

### ISSUE THREAD

**Issue by arashthk** [Flolagale/mailin#126]
mailin works pretty much all the time with no exception, but sometimes out of nowhere I get `ENENT` error:

```
error: 711463a6-4622-487f-9efd-0fcbfcdd40da Unable to finish processing message!! Error: ENOENT: no such file or directory, open '.tmp/711463a6-4622-487f-9efd-0fcbfcdd40da' 
    at Error (native) 
error: Error: ENOENT: no such file or directory, open '.tmp/711463a6-4622-487f-9efd-0fcbfcdd40da' 
    at Error (native) 
Unhandled rejection Error: ENOENT: no such file or directory, open '.tmp/711463a6-4622-487f-9efd-0fcbfcdd40da' 
    at Error (native) 
```

And that's it! Does anyone have any clue?
I run mailin CLI as sudo and webhook it set.

node version: v6.10.3
mailin version: 3.0.4
Ubuntu 14.04

**Comment by ghost** [comment]
I've seen the same situation, I am roughly losing 17 out of 1,500 emails within a 2 minutes timespan.
The error message is the same:

error: Error: ENOENT: no such file or directory, open '.tmp/8ccdbca8-6918-4e93-812a-b53c8538a1d6'
    at Error (native)
From previous event:
    at retrieveRawEmail (/tmp/node_modules/mailin/lib/mailin.js:237:19)
    at dataReady (/tmp/node_modules/mailin/lib/mailin.js:205:16)
    at PassThrough.<anonymous> (/tmp/node_modules/mailin/lib/mailin.js:440:13)
    at emitNone (events.js:91:20)
    at PassThrough.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
Unhandled rejection Error: ENOENT: no such file or directory, open '.tmp/8ccdbca8-6918-4e93-812a-b53c8538a1d6'
    at Error (native)

I'm using (also webhook):

"mailin": "3.0.4",
FROM node:6.10.2-alpine
On a Mac

**Comment by orval** [comment]
Also seeing this.

node: v6.11.2
mailin: 1.0.0
OpenBSD 6.2
