### ISSUE TITLE
I use sample code, when run got a error.

### ISSUE THREAD

**Issue by panxw** [Flolagale/mailin#129]
node server.js

```

error: Error: listen EACCES 0.0.0.0:25
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1245:19)
    at listen (net.js:1294:10)
    at net.js:1404:9
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
events.js:165
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (undefined)
    at Mailin.emit (events.js:163:17)
    at SMTPServer.<anonymous> (/home/panxuewen/mailin/node_modules/mailin/lib/mailin.js:519:15)
    at emitOne (events.js:96:13)
    at SMTPServer.emit (events.js:188:7)
    at SMTPServer._onError (/home/panxuewen/mailin/node_modules/smtp-server/lib/smtp-server.js:237:10)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
```

**Comment by arashthk** [comment]
Port 25 is occupied. Use `netstat` on Linux or `lsof` on macos to findout who's listening on it.
Then you can either terminate that program or start mailin by listening to another port.

**Comment by panxw** [comment]
@arashthk 
I stop nginx(it tooked 25 port), then tried, still printed the logs above.

**Comment by panxw** [comment]
Lastly ok by run:
```
sudo /usr/local/nodejs/bin/node server.js
```
@arashthk thanks!

**Comment by arashthk** [comment]
@panxw Oh you're right, my mistake! `EADDRINUSE` is because of port occupation. `EACCESS` is caused by trying to listen on ports under 1024.
