### ISSUE TITLE
mailin/node_modules/mailparser/node_modules/uue/uue.js:184    matches.forEach(nextMatch => {

### ISSUE THREAD

**Issue by DoctorOgg** [Flolagale/mailin#133]
freshly installed amazon linux machine (ami-6df1e514), and i could use some help resolving this issue...

```bash
$ node -v
v0.12.4

$ npm -v
2.10.1
```

```bash
$ npm -g install mailin
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated mimelib@0.2.19: This module is deprecated
npm WARN engine mime@1.6.0: wanted: {"node":">=4"} (current: {"node":"0.12.4","npm":"2.10.1"})
npm WARN optional dep failed, continuing fsevents@1.1.3
/usr/local/bin/mailin -> /usr/local/lib/node_modules/mailin/run-cli.js
mailin@3.0.4 /usr/local/lib/node_modules/mailin
├── spamc@0.0.5
├── extend@2.0.1
├── commander@2.13.0
├── semver@5.5.0
├── node-uuid@1.4.8
├── shelljs@0.5.3
├── languagedetect@1.1.1
├── smtp-server@1.17.0 (ipv6-normalize@1.0.1, nodemailer-shared@1.1.0)
├── html-to-text@1.6.2 (underscore.string@2.4.0, underscore@1.8.3, htmlparser@1.7.7, optimist@0.6.1)
├── bluebird@2.11.0
├── winston@1.1.2 (cycle@1.0.3, stack-trace@0.0.10, eyes@0.1.8, isstream@0.1.2, pkginfo@0.3.1, async@1.0.0, colors@1.0.3)
├── mailparser@0.5.3 (mime@1.6.0, mimelib@0.2.19, uue@3.1.1, encoding@0.1.12)
├── superagent@1.8.5 (methods@1.1.2, component-emitter@1.2.1, cookiejar@2.0.6, reduce-component@1.0.1, extend@3.0.0, mime@1.3.4, formidable@1.0.17, qs@2.3.3, debug@2.6.9, readable-stream@1.0.27-1, form-data@1.0.0-rc3)
├── forever-monitor@1.7.1 (minimatch@3.0.4, ps-tree@0.0.3, utile@0.2.1, chokidar@1.7.0, broadway@0.3.6)
└── lodash@3.10.1
```

```bash
$ mailin
/usr/local/lib/node_modules/mailin/node_modules/mailparser/node_modules/uue/uue.js:184
   matches.forEach(nextMatch => {
                             ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/mailin/node_modules/mailparser/lib/streams.js:8:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
info: Mailin stopped.
```

Thanks!

**Comment by DoctorOgg** [comment]
ok, newer node fixes, going to close this.
