### ISSUE TITLE
What's the latest version of Node you have this working on?

### ISSUE THREAD

**Issue by NickSutton** [Flolagale/mailin#141]
Hi,

Appreciate this project appears long dead. I upgraded to Node 14 and whilst MailIn appears to start ok, I'm not seeing any of the listeners fire on event like they should (and did previously)

I think I'll need to downgrade , but wondering what the latest version of Node that MailIn will work with?

**Comment by hi2u** [comment]
* Up until today (2024-04-13), I had it running fine on Node v16.20.2 on Debian.
* I upgraded to Node v20.5.1 today, and it's no longer working.  
* When a new email comes in, it dies with:

```
/usr/local/lib/npm/lib/node_modules/mailin/node_modules/smtp-server/lib/smtp-stream.js:38
    this.closed = false;
                ^

TypeError: Cannot set property closed of #<Writable> which has only a getter
    at new SMTPStream (/usr/local/lib/npm/lib/node_modules/mailin/node_modules/smtp-server/lib/smtp-stream.js:38:17)
    at new SMTPConnection (/usr/local/lib/npm/lib/node_modules/mailin/node_modules/smtp-server/lib/smtp-connection.js:54:20)
    at SMTPServer.connect (/usr/local/lib/npm/lib/node_modules/mailin/node_modules/smtp-server/lib/smtp-server.js:95:22)
    at SMTPServer.<anonymous> (/usr/local/lib/npm/lib/node_modules/mailin/node_modules/smtp-server/lib/smtp-server.js:84:14)
    at Server.emit (node:events:514:28)
    at TCP.onconnection (node:net:2157:8)
```

**Comment by y-nk** [comment]
@hi2u i think your comment is the latest up to date i could find.

there's this https://github.com/Flolagale/mailin/issues/137#issuecomment-823446983 from 2021 claiming a fork, but the fork is dead too... but there's a fork of the fork claiming it works with node18 https://github.com/vithalreddy/node-mailin/issues/41 but somebody complains the same as you. https://github.com/vithalreddy/node-mailin/issues/35#issuecomment-1783798198

i'm looking for an updated fork which could run in node20. did you find any?

**Comment by hi2u** [comment]
@y-nk Sorry, only just noticed your comment now.

No I didn't find anything that worked well as a drop-in replacement.

I ended up giving up on that setup, and switching to doing everything inside my own node app using these 2 packages instead:

- https://www.npmjs.com/package/smtp-server
- https://www.npmjs.com/package/mailparser

**Comment by y-nk** [comment]
@hi2u no pb :) in the end i got it running in node20 like a breeze but with pnpm overrides. it's a bit sad tho but it seems holding well enough for now.
