### ISSUE TITLE
read ETIMEDOUT error

### ISSUE THREAD

**Issue by hebrew878** [Flolagale/mailin#98]
error: Error: read ETIMEDOUT
    at exports._errnoException (util.js:870:11)
    at TCP.onread (net.js:552:26)
events.js:146
      throw err;
      ^

Error: Uncaught, unspecified "error" event. ([object Object])
    at emit (events.js:144:17)
    at SMTPServer.<anonymous> (/root/node_modules/mailin/lib/mailin.js:519:15)
    at emitOne (events.js:77:13)
    at SMTPServer.emit (events.js:169:7)
    at SMTPServer._onError (/root/node_modules/mailin/node_modules/smtp-server/lib/smtp-server.js:231:10)
    at emitOne (events.js:77:13)
    at SMTPConnection.emit (events.js:169:7)
    at SMTPConnection._onError (/root/node_modules/mailin/node_modules/smtp-server/lib/smtp-connection.js:249:10)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

i am using mailin inside node app and it stopped after giving this error. any help would be appreciated. 
thanks.

**Comment by Kickers** [comment]
me too!

**Comment by dudilugasi** [comment]
me Three

**Comment by aaronryden** [comment]
happening here too

**Comment by dweremeichik** [comment]
Anyone ever figure out what is/was causing this?

**Comment by vithalreddy** [comment]
Did anyone solve this?

**Comment by dweremeichik** [comment]
I stopped using mailin due to the numerous issues, and made a slightly less feature full version (not currently open source) using an up to date version of smtp-server. It solved a ton of problems for me. Mailin is on 1.x.x of smtp-server. I believe that the current version of smtp-server is 3.x.x.

**Comment by vithalreddy** [comment]
@dweremeichik , Do You have any plans to make it opensource?
love to contribute though.

**Comment by dweremeichik** [comment]
Hadn't really given it much thought. At the moment it does have code in it that I can't open up. 
I will say that mailin doesn't do any major magic here. The newer versions of smtp-server will get you at least 70% of where you need to be (out of the box, it doesn't parse HTML email, if there is a plaintext multipart you should be okay).
Perhaps down the road I might open it up, but what I have needs quite a bit of work to stand up to what mailin used to / is supposed to be. (Currently I don't use web hooks, I dump directly into a database.)

**Comment by vithalreddy** [comment]
@dweremeichik  cool!
if you ever changed your mind do ping me.
for now, I will change SMTP-server to latest one.
Thanks.

**Comment by vithalreddy** [comment]
@dweremeichik,  I have updated all the dependencies and removed webhooks and replaced mailrparser with mailparse npm module, with all tests passing if u want to take a look [Node-Mailin](https://github.com/vithalreddy/node-mailin).
